management:
  endpoints:
    enabled-by-default: true
  info:
    enabled: true

spring:
  h2:
    console.enabled: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  main:
    allow-bean-definition-overriding: true

